### PR TITLE
New language

### PR DESCRIPTION
**Pull request by hatry4**
I added Filipino and, japanese i used google in japanese 👍

### CODE REVIEW

**Comment by appujet** [comment]
please update your language  with new 1ce8fd57da7bf3f059feaf0216294b59508b0ede

**Comment by appujet** [comment]
Please complete hole json then request to pr

**Comment by hatry4** [comment]
done just finished japanese.json

**Comment by LucasB25** [comment]
There are things missing

**Comment by hatry4** [comment]
i will create new pr

**Pull request closed without merging**
